export const LOAD_SCORES_REQUEST = 'LOAD_SCORES_REQUEST';
export const LOAD_SCORES_SUCCESS = 'LOAD_SCORES_SUCCESS';
export const LOAD_SCORES_FAILURE = 'LOAD_SCORES_FAILURE';

export const LOAD_SCORE_REQUEST = 'LOAD_SCORE_REQUEST';
export const LOAD_SCORE_SUCCESS = 'LOAD_SCORE_SUCCESS';
export const LOAD_SCORE_FAILURE = 'LOAD_SCORE_FAILURE';
